# Generated by Django 5.1.2 on 2024-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventLogOutbox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("event_date_time", models.DateTimeField(db_index=True)),
                ("environment", models.CharField(db_index=True, max_length=20)),
                ("event_context", models.TextField()),
                ("is_sent", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "db_table": "event_log_outbox",
            },
        ),
    ]
